[package]
name = "worker"
version = "0.1.0"
edition = "2024"

[dependencies]
bs58 = "0.5.1"
rand = "0.9.2"
serde = "1.0.228"
solana-sdk = "3.0.0"
x25519-dalek = "2"
aes-gcm = "0.10"
hkdf = "0.12"
sha2 = "0.10"
zeroize = "1.8.2"
base64 = "0.22"
